os: linux
dist: bionic
language: python
python:
  # - "3.5"
  # 3.5 doesn't support f format string
  - "3.6"
  - "3.7"
  - "3.8"

services:
  - mysql
  - redis-server
env:
  global:
    - DJANGO_SETTINGS_MODULE="mysite.settings.pro"
branches:
    only:
        - chat
# command to install dependencies
before_install:
  - sudo apt-get update
  - sudo mkdir /var/log/django
  - sudo chown `whoami`:`whoami` /var/log/django
addons:
  apt:
    packages:
    - python-dev
    - python3-dev
    - libmysqlclient-dev
install:
  - pip install -r requirements.txt
  - pip install python-coveralls
  - pip install coverage codecov
# command to run tests
script:
    - coverage run --source="." manage.py test --settings=mysite.settings.pro --parallel
after_success:
    - coverage report
